#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
compton --config ~/.config/compton/compton.conf &

light-locker &
dunst &
nitrogen --restore 
bash ~/.config/polybar/forest/launch.sh &
#bash ~/.config/polybar/savitar/launch.sh &
#xrandr -s 1920x1200 &
xrandr --auto
#picom -f &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V 

#### BSPWM configuration ####
#bspc config border_radius                8

bspc config border_width        2 
bspc config window_gap          9 

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a thunar desktop='^3'
bspc rule -a Spotify desktop='^5'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

