import = [
  #"~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font"

#regular
size = 10.5

#for video
# size = 35.0
